<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/idlista/<?= $this->view->idlista; ?>" method="post" id="form">
                            <input type="hidden" name="biddings_id" value="<?= $this->view->idlista; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text"
                                               name="number"
                                               id="number"
                                               placeholder="Número do Item"
                                               class="form-control"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                               name="name"
                                               id="name"
                                               placeholder="Nome do Item da Licitação"
                                               class="form-control"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Ingrediente</label>
                                        <select name="ingredients_id" class="form-control" required>
                                            <?php foreach ($this->view->resultIngredients as $value): ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label>Fornecedor</label>
                                        <select name="suppliers_id" class="form-control" required>
                                            <?php foreach ($this->view->resultFornecedor as $value): ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>UF</label>
                                        <input type="text"
                                               name="uf"
                                               id="uf"
                                               placeholder="Unidade de Fornecimento do Item"
                                               class="form-control"
                                               maxlength="4"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Quantidade</label>
                                        <input type="text"
                                               name="quantity"
                                               id="quantity"
                                               placeholder="Quantidade Licitada"
                                               class="form-control"
                                               maxlength="50"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Valor</label>
                                        <input type="text"
                                               name="value"
                                               id="value"
                                               data-mask="000.000.000,00"
                                               data-mask-reverse="true"
                                               placeholder="Valor do item"
                                               class="form-control"
                                               maxlength="12"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Habilitar Item para pedidos?</label>
                                        <input type="checkbox"
                                               name="active"
                                               id="active" checked> <span class='label label-danger'>SIM!</span>
                                    </div>

                                    <div class="form-group">
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idlista; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>