<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Itens da Licitação</h3>
                <div class="alert alert-info" role="alert">
                    Númeno: <strong><?= $this->view->resultLicitacao['numero']; ?></strong><br>
                    UASG: <strong><?= $this->view->resultLicitacao['uasg']; ?></strong><br>
                    Órgão: <strong><?= $this->view->resultLicitacao['nome_uasg']; ?></strong>
                </div>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?= $this->view->controller; ?>novo/idlista/<?= $this->view->idLista; ?>" class="btn btn-info">
                    <i class="fa fa-plus-circle"></i> Novo Registro
                </a>
                <div class="row">
                    <div class="col-md-6">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <?php foreach ($this->view->btn['link'] as $value): ?>
                                    <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                        <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $value; ?>">
                                            <?= $value; ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                                <li>
                                    <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Qtd(Inicial)</th>
                            <th>Valor</th>
                            <th>UF</th>
                            <th>Habil.</th>
                            <th>Nome</th>
                            <th>Fornecedor</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td style='font-size: 11px'><?= $value['numero']; ?></td>
                                <td style='font-size: 11px'><?= $value['quantidade']; ?></td>
                                <td style='font-size: 11px'>R$ <?= number_format($value['valor'], 2, ',', '.'); ?></td>
                                <td style='font-size: 11px'><?= $value['uf']; ?></td>
                                <td style='font-size: 11px'>
                                    <span class='label label-<?= $value['active'] ? 'success' : 'danger'; ?>'>
                                        <?= $value['active'] ? 'Sim' : 'Não'; ?>
                                    </span>
                                </td>
                                <td style='font-size: 11px'><?= $value['nome']; ?></td>
                                <td style='font-size: 11px'>
                                    <?= strlen($value['fornecedor']) > 25 ? substr($value['fornecedor'], 0, 25) . '...' : $value['fornecedor']; ?>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idLista; ?>" class="btn btn-default btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="#"
                                       onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idLista; ?>')"
                                       class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $value; ?>">
                                    <?= $value; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>listar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
