<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
            <div class="resultado"></div>
        </div>
        <form action="<?= $this->view->controller; ?>alteraMenuDays/" method="post" id="form">
            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                        </div>
                        <div class="card-body">
                            <div id="resultado"></div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Início</label>
                                        <input type="text"
                                            id="beginningDate"
                                            name="beginningDate"
                                            placeholder="Data no formato DD-MM-AAAA"
                                            class="form-control"
                                            data-mask="00-00-0000"
                                            value="<?= date("d-m-Y", strtotime($this->view->result['beginning_date'])) ?>"
                                            required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Final</label>
                                        <input type="text"
                                            id="endingDate"
                                            name="endingDate"
                                            placeholder="Data no formato DD-MM-AAAA"
                                            class="form-control"
                                            data-mask="00-00-0000"
                                            value="<?= date("d-m-Y", strtotime($this->view->result['ending_date'])) ?>"
                                            disabled
                                            required>
                                    </div>
                                    <div class="form-group pull-right">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar data</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>        
    </div>
</div>