<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="card-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Início</label>
                                        <input type="text"
                                               id="beginning_date"
                                               name="beginning_date"
                                               placeholder="Data no formato DD-MM-YYYY"
                                               class="form-control"
                                               data-mask="00-00-0000"
                                               required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Final</label>
                                        <input type="text"
                                               id="ending_date"
                                               name="ending_date"
                                               placeholder="Data no formato DD-MM-YYYY"
                                               class="form-control"
                                               data-mask="00-00-0000"
                                               required>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>