<?php

use App\Helpers\View;

$menusId = $this->getParametro('id');

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
            <div class="resultado"></div>
        </div>
        <div class="row">
            <div class="col-md-6">
            <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->result['status'] == 'ABERTO'): ?>
                <a href="<?= $this->view->controller ?>aprovar/id/<?= $this->view->result['id'] ?>" class="btn btn-success">
                    <i class="fa fa-check"></i> Aprovar cardápio
                </a>
            <?php endif; ?>
            <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->result['status'] == 'APROVADO'): ?>
                <a href="<?= $this->view->controller; ?>gerarSolicitacoes/id/<?= $this->view->result['id']; ?>" class="btn btn-success">
                    <i class="fa fa-check"></i> Gerar solicitações
                </a>
            <?php endif; ?>
            <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO'])): ?>
                <a href="<?= $this->view->controller; ?>itensNaoLicitados/id/<?= $this->view->result['id']; ?>" class="btn btn-primary">
                    <i class="fa fa-list"></i> Itens não licitados
                </a>
            <?php endif; ?>
            </div>
            <div class="col-md-6">
                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
            </div>
        </div>
        <div id="resultado"></div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-table fa-fw"></i> Data do cardápio
                    </div>
                    <div class="card-body">
                        <form action="<?= $this->view->controller; ?>alteraMenuDays/" method="post" id="form">
                        <input type="hidden" name="id" id="menusId" value="<?= $this->view->result['id']; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Início</label>
                                        <input type="text"
                                            id="beginningDate"
                                            name="beginningDate"
                                            placeholder="Data no formato DD-MM-AAAA"
                                            class="form-control"
                                            data-mask="00-00-0000"
                                            value="<?= date("d-m-Y", strtotime($this->view->result['beginning_date'])) ?>"
                                            required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Final</label>
                                        <input type="text"
                                            id="endingDate"
                                            name="endingDate"
                                            placeholder="Data no formato DD-MM-AAAA"
                                            class="form-control"
                                            data-mask="00-00-0000"
                                            value="<?= date("d-m-Y", strtotime($this->view->result['ending_date'])) ?>"
                                            disabled
                                            required>
                                    </div>
                                    <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->result['status'] == 'ABERTO'): ?>
                                    <div class="form-group pull-right">
                                        <br>
                                        <button class="btn btn-info"><i class="fa fa-refresh"></i> Atualizar data</button>
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header title-menu">
                        Receitas do cardápio
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Data</th>
                                        <th>Refeição</th>
                                        <th>Receita</th>
                                        <th>Quantidade de pessoas</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->view->recipes as $value): ?>
                                    <tr>
                                        <td><?= View::humanDate($value['date']); ?></td>
                                        <td><?= $value['meals'] ?></td>
                                        <td><?= $value['recipes'] ?></td>
                                        <td><?= $value['quantity_people'] ?></td>
                                        <td>
                                            <a href="<?= $this->view->controller; ?>detalharItems/idRecipes/<?= $value['id']; ?>/menusId/<?= $menusId; ?>" class="btn btn-primary btn-sm">
                                                <i class="fa fa-list"></i> Ingredientes
                                            </a>
                                            <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->result['status'] == 'ABERTO'): ?>
                                            <a href="<?= $this->view->controller; ?>editarRecipes/idRecipes/<?= $value['id']; ?>/menusId/<?= $menusId; ?>" class="btn btn-success btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a
                                                onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>/menusId/<?= $menusId; ?>')"
                                                class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->result['status'] == 'APROVADO'): ?>
                        <div class="col-lg-12">
                            <div class="form-group pull-right">
                                <br>
                                <a href="<?= $this->view->controller; ?>gerarSolicitacoes/id/<?= $this->view->result['id']; ?>" class="btn btn-success">
                                    <i class="fa fa-check"></i> Gerar solicitações
                                </a>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function () {
    var beginningDate = $("#beginningDate");
    var endingDate = $("#endingDate");
    var menuJson = [];
    var itemsMap = [];
    var menuMap = [];
    var currentDay = 1;
    var currentDayObj = {};
    var x = 1;

    /**
     * Reverse the Date in portuguese format to english format
     * @param { String } Value
     * @return { String }
     */
    var reverseDate = function rverseDate(value) {
        return value && value.split("-").reverse().join("-");
    };

    beginningDate.on("blur", function () {
        if (validateDate(beginningDate.val())) {
            var day = new Date(reverseDate(beginningDate.val()));
            var nextWeek = new Date(day.getTime() + 7 * 86400000);
            endingDate.val(formatDate(nextWeek));
        }
    });

    function formatDate(dateVal) {
        var month = dateVal.getMonth() + 1;
        var day = dateVal.getDate();

        var output =
                (day < 10 ? '0' : '') + day + '-' +
                (month < 10 ? '0' : '') + month + '-' +
                dateVal.getFullYear();

        return output;
    }

    /**
     * Teste if the date is DD-MM-AAAA
     * @param { String } date
     * @return { Boolean }
     */
    function validateDate(date) {
        var regexDate = /^(0[1-9]|1\d|2\d|3[01])-(0[1-9]|1[0-2])-(19|20)\d{2}$/;
        return regexDate.test(date);
    }
});
</script>