<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>            
        </div>
        <div id="resultado"></div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-table fa-fw"></i> Ingrediente da receita
                    </div>
                    <div class="card-body">
                        <form action="<?= $this->view->controller; ?>alteraItems/" method="post" id="form">
                        <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">                            
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Ingrediente</label>
                                        <input type="text"
                                            id="name"
                                            name="name"
                                            class="form-control"
                                            value="<?= $this->view->result['name'] ?>"
                                            disabled>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Quantidade</label>
                                        <input type="text"
                                            id="quantity"
                                            name="quantity"
                                            class="form-control"
                                            data-mask="#.###"
                                            maxlength="5"
                                            value="<?= $this->view->result['quantity'] ?>"
                                            required>
                                    </div>
                                    <div class="form-group pull-right">
                                        <br>
                                        <button class="btn btn-success"><i class="fa fa-check"></i> Atualizar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>