<?php

use App\Helpers\View;

$menusId = $this->getParametro('id');

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Itens não licitados do cardápio</h5>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <a href="<?= $this->view->controller; ?>detalhar/id/<?= $menusId ?>" class="btn btn-warning pull-right">
                            <i class="fa fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Quantidade</th>
                            <th>UF</th>
                            <th>Dia</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->view->result as $value): ?>
                        <tr>
                            <td><?= $value['name'] ?></td>
                            <td><?= $value['quantity'] ?></td>
                            <td><?= $value['uf'] ?></td>
                            <td><?= View::humanDate($value['date']) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>