<?php
@http_response_code(404);

?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title>Erro 404 - Página não encontrada</title>

        <style type="text/css">
            @font-face {
                font-family: 'Capriola';
                font-style: normal;
                font-weight: 400;
                src: local('Capriola Regular'), local('Capriola-Regular'),
                    url('/font/uuDFYyWaIr7gMYVZu_PK5fesZW2xOQ-xsNqO47m55DA.woff') format('woff');
            }
            body{
                font-family: 'Capriola', sans-serif;
            }
            body{
                background:#DAD6CC;
            }
            .wrap{
                margin:0 auto;
                width:1000px;
            }
            .logo h1{
                font-size:200px;
                color:#FF7A00;
                text-align:center;
                margin-bottom:1px;
                text-shadow:4px 4px 1px white;
            }
            .logo p{
                color:#B1A18D;;
                font-size:20px;
                margin-top:1px;
                text-align:center;
            }
            .logo p span{
                color:lightgreen;
            }
            .sub a{
                color:#ff7a00;
                text-decoration:none;
                padding:5px;
                font-size:13px;
                font-family: arial, serif;
                font-weight:bold;
            }
            .footer{
                color:white;
                position:absolute;
                right:10px;
                bottom:10px;
            }
            .footer a{
                color:#ff7a00;
            }
        </style>
    </head>


    <body>
        <div class="wrap">
            <div class="logo">
                <h1>404</h1>
                <p> Opss - Arquivo ou página não encontrados!</p>
                <div class="sub">
                    <p><a href="<?php echo App\Config\Configurations::DEFAULT_URI; ?>"> Voltar ao Início</a></p>
                </div>
            </div>
        </div>

        <div class="footer">
            <a href="mailto:bruno.monteirodg@gmail.com">PHB Sistemas Web</a>
        </div>

    </body>
</html>
