<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                               id="nome"
                                               name="nome"
                                               placeholder="Nome da Empresa"
                                               class="form-control"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>CNPJ</label>
                                        <input type="text"
                                               id="cnpj"
                                               name="cnpj"
                                               placeholder="CNPJ do Fornecedor"
                                               class="form-control"
                                               maxlength="18"
                                               required>
                                        <p class="help-block">Ex.: 00.000.000/0001-00</p>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Dados da Empresa</label>
                                        <textarea
                                            name="dados"
                                            id="dados"
                                            placeholder="Fone, E-mail, endereço ... Ex.: Rua dos Almirantes, nº 171, Reduto - Belém - Pa, (91) 3745-2766 - contato@empresa.com.br"
                                            class="form-control"
                                            required></textarea>
                                        <p class="help-block">Endereço, Contato...</p>
                                    </div>

                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>