<?php
$cfg = App\Config\Configurations::htrFileConfigs();
?>
<script src="attach/Chart.js-master/Chart.min.js"></script>
<script>
    var barChartData = {
        labels: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
        datasets: [
            {
                fillColor: "rgba(151,187,205,0.5)",
                strokeColor: "rgba(151,187,205,0.8)",
                highlightFill: "rgba(151,187,205,0.75)",
                highlightStroke: "rgba(151,187,205,1)",
                data: [<?= $this->view->chart; ?>]
            }
        ]

    };
    window.onload = function () {
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myBar = new Chart(ctx).Bar(barChartData, {
            responsive: true
        });
    };

</script>
<div id="page-wrapper">
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        </div>

        <!-- Content Row -->
        <div class="row">

            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Fornecedores</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= count($this->view->fornecedor); ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-suitcase fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Solicitações (mensal)</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $this->view->solicitacoesMensal['quantidade'] ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-list fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Aguard. aprov.</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $this->view->pendAprov['quantidade'] ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-thumbs-up fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        </div>

        <?php foreach ($this->view->resultAvisos ?? [] as $value): ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-bullhorn fa-fw"></i> <?= $value['titulo'] ?? ''; ?>
                        </div>
                        <div class="panel-body">
                            <div class="row well-sm">
                                <?= $value['corpo'] ?? ''; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="row">
            <div class="col-lg-12">
                <h3>Gráfico de Solicitações em <?= date("Y"); ?></h3>
                <canvas id="canvas" height="90"></canvas>
            </div>
        </div>
        <div class="row">
            <!--div class="col-lg-6 mb-4">

                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Melhores empresas avaliadas</h6>
                    </div>
                    <div class="card-body">
                        <?php foreach ($this->view->melhoresAvaliacoes as $value): ?>
                        <h4 class="small font-weight-bold">
                            <?= $value['nome'] ?>
                            <span class="float-right"><?= $value['nota'] ?></span>
                        </h4>
                        <div class="progress mb-4">
                            <div class="progress-bar bg-danger"
                                 role="progressbar"
                                 style="width: <?= $value['nota'] ?>%"
                                 aria-valuenow="<?= $value['nota'] ?>"
                                 aria-valuemin="0"
                                 aria-valuemax="100"></div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 mb-4">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Piores empresas avaliadas</h6>
                    </div>
                    <div class="card-body">
                        <?php foreach ($this->view->pioresAvaliacoes as $value): ?>
                        <h4 class="small font-weight-bold">
                            <?= $value['nome'] ?>
                            <span class="float-right"><?= $value['nota'] ?></span>
                        </h4>
                        <div class="progress mb-4">
                            <div class="progress-bar bg-danger"
                                 role="progressbar"
                                 style="width: <?= $value['nota'] ?>%"
                                 aria-valuenow="<?= $value['nota'] ?>"
                                 aria-valuemin="0"
                                 aria-valuemax="100"></div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div-->
        </div>
    </div>
