<?php
$cfg = App\Config\Configurations::htrFileConfigs();

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <?php foreach ($this->view->resultAvisos ?? [] as $value): ?>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card bg-warning shadow billboard-container">
                        <div class="card-body billboard-content">
                            <div class="billboard-title">
                                <i class="fa fa-bullhorn fa-fw"></i> <?= $value['titulo'] ?? ''; ?>
                            </div>
                            <div class="billboard-body">
                                <?= $value['corpo'] ?? ''; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <!-- Content Row -->
        <div class="row">
            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Fornecedores</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= count($this->view->fornecedor); ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-suitcase fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Solicitações (mensal)</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $this->view->solicitacoesMensal['quantidade'] ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-list fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Aguard. aprov.</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $this->view->pendAprov['quantidade'] ?></div>
                            </div>
                            <div class="col-auto">
                                <i class="fa fa-thumbs-up fa-fw"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6 mb-4">
            <div class="card shadow">
                <div class="card-header py-1">
                    <h6 class="m-0 font-weight-bold text-primary">Melhores empresas avaliadas</h6>
                </div>
                <div class="card-body">
                    <?php foreach ($this->view->melhoresAvaliacoes as $index => $value): ?>
                        <?php
                        if ($index > 4) {
                            break;
                        }
                        $value['nota'] = round($value['nota'], 2);

                        ?>
                        <h4 class="small font-weight-bold">
                            <?= $value['nome'] ?>
                            <span class="float-right"><?= $value['nota'] ?></span>
                        </h4>
                        <div class="progress mb-4">
                            <div class="progress-bar bg-success"
                                 role="progressbar"
                                 style="width: <?= ($value['nota'] * 100) / 5 ?>%"
                                 aria-valuenow="<?= $value['nota'] ?>"
                                 aria-valuemin="1"
                                 aria-valuemax="5"></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div class="col-lg-6 mb-4">
            <div class="card shadow">
                <div class="card-header py-1">
                    <h6 class="m-0 font-weight-bold text-primary">Piores empresas avaliadas</h6>
                </div>
                <div class="card-body">
                    <?php foreach ($this->view->pioresAvaliacoes as $index => $value): ?>
                        <?php
                        if ($index > 4) {
                            break;
                        }
                        $value['nota'] = round($value['nota'], 2);

                        ?>
                        <h4 class="small font-weight-bold">
                            <?= $value['nome'] ?>
                            <span class="float-right"><?= $value['nota'] ?></span>
                        </h4>
                        <div class="progress mb-4">
                            <div class="progress-bar bg-danger"
                                 role="progressbar"
                                 style="width: <?= ($value['nota'] * 100) / 5 ?>%"
                                 aria-valuenow="<?= $value['nota'] ?>"
                                 aria-valuemin="0"
                                 aria-valuemax="5"></div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card shadow">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Últimas solicitações atualizadas
                    </h6>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>
                                    Número
                                </th>
                                <th>
                                    OM
                                </th>
                                <th>
                                    Status
                                </th>
                                <th>
                                    Atualização
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->lastUpdated as $value): ?>
                                <tr>
                                    <td><?= $value['numero']; ?></td>
                                    <td><?= $value['indicativo_naval']; ?></td>
                                    <td><?= $value['status']; ?></td>
                                    <td><?= date('d-m-Y H:i:s', $value['updated_at']); ?></td>
                                    <td>
                                        <a href="solicitacao/ver/busca/<?= $value['numero']; ?>" class="btn btn-dark btn-sm">
                                            <i class="fa fa-arrow-circle-right"></i> Ver Solicitação
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .btn-dark {
        color: #fff !important;
    }
</style>
