<?php
$formatDate = function(string $value) {
    $explodedDate = explode('-', $value);
    $explodedDate = array_reverse($explodedDate);
    return implode('-', $explodedDate);
};

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>
        <form action="<?= $this->view->controller; ?>altera/" method="post" id="form">
            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
            <div class="row">
                <div class="col-lg-12">
                    <div id="resultado"></div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-table fa-fw"></i> Dados do Aviso
                        </div>
                        <div class="panel-body">
                            <div class="row" style="margin-top: 10px;">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Título</label>
                                        <input type="text"
                                               id="titulo"
                                               name="titulo"
                                               placeholder="Título do aviso"
                                               class="form-control"
                                               value="<?= $this->view->result['titulo']; ?>"
                                               required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Início</label>
                                        <input type="text"
                                               id="data_inicio"
                                               name="data_inicio"
                                               placeholder="Data no formato DD-MM-YYYY"
                                               class="form-control"
                                               value="<?= $formatDate($this->view->result['data_inicio']); ?>"
                                               data-mask="00-00-0000"
                                               required>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data de Final</label>
                                        <input type="text"
                                               id="data_fim"
                                               name="data_fim"
                                               placeholder="Data no formato DD-MM-YYYY"
                                               class="form-control"
                                               value="<?= $formatDate($this->view->result['data_fim']); ?>"
                                               data-mask="00-00-0000"
                                               required>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Mensagem</label>
                                        <textarea
                                            maxlength="256"
                                            name="corpo"
                                            id="corpo"
                                            class="form-control"
                                            required><?= $this->view->result['corpo']; ?></textarea>
                                        <p class="help-block">
                                            <i class="fa fa-info-circle"></i> Mensagem com
                                            <span class="text-danger">
                                                256 caracteres
                                            </span>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <button class="btn btn-success">
                                            <i class="fa fa-check"></i> Atualizar
                                        </button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> OMs Registradas para este aviso
                        <a href="<?= $this->view->controller; ?>adicionarom/id/<?= $this->view->result['id']; ?>"
                           class="btn btn-info pull-right"
                           style="margin-top: -7px;">
                            <i class="fa fa-plus-circle"></i> Adicionar OM
                        </a>
                    </div>
                    <div class="panel-body">
                        <div class="row" style="margin-top: 10px;">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Indicativo Naval</th>
                                        <th>Nome</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->view->resultOms as $value): ?>
                                        <tr>
                                            <td><?= $value['indicativo_naval'] ?? ''; ?></td>
                                            <td><?= $value['nome'] ?? ''; ?></td>
                                            <td>
                                                <a
                                                    onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminarom/id/<?= $value['id']; ?>/avisoid/<?= $this->view->result['id']; ?>')"
                                                    class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>