<?php
$id = $this->getParametro('id');

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> OMs
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registrarnovaom" method="post" id="form">
                            <input type="hidden" name="id" value="<?= $id ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>OM Disponível</label>
                                        <select name="oms" class="form-control" required>
                                            <?php foreach ($this->view->result as $value): ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                    -
                                                    <?= $value['name']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <button class="btn btn-success">
                                            <i class="fa fa-check"></i> Adicionar
                                        </button>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $id; ?>" class="btn btn-warning">
                                            <i class="fa fa-arrow-left"></i> Voltar
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>