<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Quadro de Avisos</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>
                <div class="row">
                    <div class="col-md-12">
                        <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                            <i class="fa fa-plus-circle"></i> Novo Registro
                        </a>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Mensagem</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= View::limitString($value['title'], 35); ?></td>
                                <td><?= View::limitString($value['content'], 35); ?></td>
                                <td>
                                    <strong class="badge badge-success">
                                        <?= View::humanDate($value['beginning_date']); ?>
                                    </strong>
                                    à 
                                    <strong class="badge badge-danger">
                                        <?= View::humanDate($value['ending_date']); ?>
                                    </strong>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a
                                        onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                        class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>