<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$formatDate = function(string $value) {
    $explodedDate = explode('-', $value);
    $explodedDate = array_reverse($explodedDate);
    return implode('-', $explodedDate);
};

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Fornecedores</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>
                <div class="row">
                    <div class="col-md-12">
                        <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                            <i class="fa fa-plus-circle"></i> Novo Registro
                        </a>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Criado Por</th>
                            <th>Título</th>
                            <th>Mensagem</th>
                            <th>Criação</th>
                            <th>Validade</th>
                            <th>Disponível para</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['usuario_criador_nome'] ?? ''; ?></td>
                                <td><?= View::limitString($value['titulo'], 35); ?></td>
                                <td><?= View::limitString($value['corpo'], 35); ?></td>
                                <td><?= $formatDate($value['created_at']); ?></td>
                                <td>
                                    <strong class="badge badge-success">
                                        <?= $formatDate($value['data_inicio']); ?>
                                    </strong>
                                    à 
                                    <strong class="badge badge-danger">
                                        <?= $formatDate($value['data_fim']); ?>
                                    </strong>
                                </td>
                                <td>
                                    <?= $value['om_quantidade']; ?>
                                    <?= $value['om_quantidade'] > 1 ? 'OMs' : 'OM'; ?>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a
                                        onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                        class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>