<?php

use App\Helpers\Pagination;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
        return [
            'previous' => "{$controllerName}solicitacao/pagina/{$btn['previous']}",
            'next' => "{$controllerName}solicitacao/pagina/{$btn['next']}",
            'current' => "{$controllerName}solicitacao/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Relatório</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <div class="row">
                    <div class="col-md-3">
                        <?= $pagination ?>
                    </div>
                </div>
                <table class="table" id="result_itens">
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>OM</th>
                            <th>NF</th>
                            <th>Tipo</th>
                            <th>Status</th>
                            <th>Entrega</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['numero']; ?></td>
                                <td><?= $value['indicativo_naval']; ?></td>
                                <td><?= $value['numero_nota_fiscal'] ?: ''; ?></td>
                                <td><?= !$value['nao_licitado'] ? '<i class="fa fa-group"></i> Lic.' : '<i class="fa fa-shopping-cart"></i> NL'; ?></td>
                                <td>
                                    <?= $value['status'] ?>
                                </td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= $value['data_entrega']; ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var btnApplySearch = $('.btn-apply-search');
        var matchesPage = window.location.href.match(/\/pagina\/(\d+)/);
        var page = matchesPage && matchesPage[1] || 1;

        btnApplySearch.click(function () {
            var selectOm = $('#om').val();
            var dateInit = $('#dateInit').val();
            var dateEnd = $('#dateEnd').val();
            var search = $('#busca').val();
            var url = 'relatorio/solicitacao/';

            if (page) {
                url += 'pagina/' + page + '/';
            }
            if (selectOm) {
                url += 'om/' + selectOm + '/';
            }
            if (dateInit) {
                url += 'dateInit/' + dateInit + '/';
            }
            if (dateEnd) {
                url += 'dateEnd/' + dateEnd + '/';
            }
            if (search) {
                url += 'busca/' + search;
            }
            window.location = url;
        });
    });
</script>