<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Config\Configurations as cfg;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
        return [
            'previous' => "{$controllerName}solicitacao/pagina/{$btn['previous']}",
            'next' => "{$controllerName}solicitacao/pagina/{$btn['next']}",
            'current' => "{$controllerName}solicitacao/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Relatório</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <div class="row">
                    <div class="col-md-3">
                        <?= $pagination ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <select
                                class="form-control"
                                name="om"
                                id="om">
                                <option value="">OM</option>
                                <?php foreach ($this->view->resultOms as $value): ?>
                                    <option value="<?= $value['id'] ?>" <?= View::isSelected($value['id'], $this->getParametro('om')); ?>>
                                        <?= $value['naval_indicative'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <select
                                class="form-control"
                                name="status"
                                id="status">
                                <option value="">Status</option>
                                <?php foreach (cfg::DEFAULT_REQUEST_STATUS as $value): ?>
                                    <option value="<?= $value ?>" <?= View::isSelected($value, $this->getParametro('status')); ?>><?= $value ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <input type="text"
                                   name="dateInit"
                                   id="dateInit"
                                   data-mask="00-00-0000"
                                   placeholder="Data de inicial"
                                   value="<?= $this->getParametro('dateInit'); ?>"
                                   class="form-control">
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <input type="text"
                                   name="dateEnd"
                                   id="dateEnd"
                                   data-mask="00-00-0000"
                                   placeholder="Data de final"
                                   value="<?= $this->getParametro('dateEnd'); ?>"
                                   class="form-control">
                        </div>
                    </div>
                    <div class="col-lg-1">
                        <button class="btn btn-info btn-apply-search">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
                <table class="table" id="result_itens">
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>OM</th>
                            <th>NF</th>
                            <th>Tipo</th>
                            <th>Status</th>
                            <th>Entrega</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td>
                                    <?= $value['requests_number']; ?>
                                </td>
                                <td>
                                    <?= $value['naval_indicative']; ?>
                                </td>
                                <td>
                                    <?= $value['invoice'] ?: ''; ?>
                                </td>
                                <td>
                                    <?= $value['biddings_id'] ? '<i class="fa fa-group"></i> Lic.' : '<i class="fa fa-shopping-cart"></i> NL'; ?>
                                </td>
                                <td>
                                    <?= $value['requests_status'] ?>
                                </td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate($value['delivery_date']); ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var btnApplySearch = $('.btn-apply-search');
        var matchesPage = window.location.href.match(/\/pagina\/(\d+)/);
        var page = matchesPage && matchesPage[1] || 1;

        btnApplySearch.click(function () {
            var selectOm = $('#om').val();
            var status = $('#status').val();
            var dateInit = $('#dateInit').val();
            var dateEnd = $('#dateEnd').val();
            var search = $('#busca').val();
            var url = 'relatorio/solicitacao/';

            if (page) {
                url += 'pagina/' + page + '/';
            }
            if (selectOm) {
                url += 'om/' + selectOm + '/';
            }
            if (status) {
                url += 'status/' + status + '/';
            }
            if (dateInit) {
                url += 'dateInit/' + dateInit + '/';
            }
            if (dateEnd) {
                url += 'dateEnd/' + dateEnd + '/';
            }
            if (search) {
                url += 'busca/' + search;
            }
            window.location = url;
        });
    });
</script>