<?php

use App\Helpers\Pagination;

$idLista = $this->view->idLista;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idLista) {
        return [
            'previous' => "{$controllerName}licitacao/idlista/{$idLista}/pagina/{$btn['previous']}",
            'next' => "{$controllerName}licitacao/idlista/{$idLista}/pagina/{$btn['next']}",
            'current' => "{$controllerName}licitacao/idlista/{$idLista}/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Relatório de Demanda</h5>
                <div class="alert alert-info" role="alert">
                    Órgão:
                    <strong>
                        <?= $this->view->resultLicitacao['uasg']; ?> - 
                        <?= $this->view->resultLicitacao['uasg_name']; ?>
                    </strong><br>
                    Númeno: <strong><?= $this->view->resultLicitacao['number']; ?></strong> | 
                    Descrição: <strong><?= $this->view->resultLicitacao['description']; ?></strong>
                </div>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>
                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                </div>
                <table class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>UF</th>
                            <th>Nome</th>
                            <th>Fornecedor</th>
                            <th>Licitado</th>
                            <th>Demanda</th>
                            <th>Restante</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td style='font-size: 11px'><?= $value['number']; ?></td>
                                <td style='font-size: 11px'><?= $value['uf']; ?></td>
                                <td style='font-size: 11px'><?= $value['name']; ?></td>
                                <td style='font-size: 11px'><?= $value['fornecedor']; ?></td>
                                <td>
                                    <span class="label label-success">
                                        <?= $value['quantity']; ?>
                                    </span>
                                </td>
                                <td>
                                    <?php
                                    $demanda = $this->demanda($value['number'], $this->view->resultLicitacao['id']);
                                    $restante = $value['quantity'] - $demanda;
                                    if ($demanda):

                                        ?>
                                        <span class="badge badge-danger">
                                            <?= $demanda ?>
                                        </span>
                                    <?php else: ?>
                                        ---
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <span class="label <?= $restante < 0 ? "label-danger" : "label-default"; ?>">
                                        <?= $restante; ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>