<?php

use App\Helpers\Pagination;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
        return [
            'previous' => "{$controllerName}demanda/pagina/{$btn['previous']}",
            'next' => "{$controllerName}demanda/pagina/{$btn['next']}",
            'current' => "{$controllerName}demanda/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Licitações Registradas</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>

                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Numero</th>
                            <th>Descrição</th>
                            <th>UASG</th>
                            <th>Órgão</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['numero']; ?></td>
                                <td><?= $value['descricao']; ?></td>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['nome_uasg']; ?></td>
                                <td>
                                    <span class="label label-danger">
                                        <?= date('d-m-Y', $value['validade']); ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>licitacao/idlista/<?= $value['id_lista']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-list"></i> Rel. Demanda
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>