<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Itens da Solicitação</h3>
                <div class="alert alert-info" role="alert">
                    Número da Solicitação: <strong><?= $this->view->resultSolicitacao['numero_solicitacao']; ?></strong><br>
                    Organização Militar: <strong><?= $this->view->resultSolicitacao['om_nome']; ?></strong><br>
                    Data da Solicitação: 
                    <span class="text-danger">
                        <?= date('d-m-Y', $this->view->resultSolicitacao['created_at']); ?>
                    </span><br>
                    Data estipulada para entrega: 
                    <span class="text-danger">
                        <?= $this->view->resultSolicitacao['data_entrega']; ?>
                    </span>
                    <br>
                    <?php if ($this->view->resultSolicitacao['nao_licitado'] == 0): ?>
                        Fornecedor: <strong><?= $this->view->resultSolicitacao['fornecedor_nome']; ?></strong><br>
                        Licitação: <strong><?= $this->view->resultLicitacao['numero']; ?></strong><br>
                        Órgão:
                        <strong>
                            <?= $this->view->resultLicitacao['uasg']; ?> - 
                            <?= $this->view->resultLicitacao['nome_uasg']; ?>
                        </strong>
                    <?php else: ?>
                        <br>
                        <strong>
                            <i class="fa fa-info-circle"></i> Não Licitado
                        </strong>
                    <?php endif; ?>
                </div>

                <i class="fa fa-list"></i> <?= $this->view->title; ?>

                <div class="row">
                    <div class="col-md-6">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <?php foreach ($this->view->btn['link'] as $value): ?>
                                    <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                        <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $value; ?>">
                                            <?= $value; ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                                <li>
                                    <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Solicitado</th>
                            <th>Fornecido</th>
                            <th>UF</th>
                            <th>Nº Item</th>
                            <th>Nome</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['item_quantidade']; ?></td>
                                <td><?= $value['item_quantidade_atendida']; ?></td>
                                <td><?= $value['item_uf']; ?></td>
                                <td><?= $value['item_numero']; ?></td>
                                <td><?= $value['item_nome']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $value; ?>">
                                    <?= $value; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->