<?php

use App\Config\Configurations as cfg;

$cfg = cfg::htrFileConfigs();

?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Edson B S Monteiro">
        <base href="//<?= cfg::DOMAIN; ?><?= cfg::DEFAULT_URI; ?>">
        <title>
            <?= $this->view->title ?? '' ?>
            <?= ' :: ' . $cfg->application->name . ' ' . $cfg->application->version . ' ::' ?>
        </title>

        <!-- Custom CSS -->
        <link href="css/sb-admin-2.min.css" rel="stylesheet">
        <link href="css/custom.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="attach/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">
            @media print {
                .btn, .pagination {
                    display: none;
                }
            }
        </style>
    </head>

    <body id="page-top">
        <!-- jQuery -->
        <script src="attach/jquery/dist/jquery.min.js"></script>
        <script src="attach/jqueryForm/jquery.form.min.js"></script>
        <div id="wrapper">

            <?php include_once cfg::PATH_CORE . '/App/Views/Layout/menu_vertical.phtml'; ?>

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <?php include_once cfg::PATH_CORE . '/App/Views/Layout/menu_horizontal_top.phtml'; ?>

                    <!-- Begin Page Content -->
                    <div class="container-fluid">

                        <?= $this->content(); ?>

                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->

                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span> <?= $cfg->application->om ?> &copy; <?= date('Y'); ?></span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->

        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-arrow-up"></i>
        </a>

        <!-- /#wrapper -->
        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.bundle.js"></script>

        <script src="js/jquery.easing.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="attach/metisMenu/dist/metisMenu.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="js/sb-admin-2.min.js"></script>

        <!-- JQuery Mask Plugin JavaScript -->
        <script src="attach/jqueryMask/jquery.mask.min.js"></script>

        <!-- Script padrão de envio de formulário -->
        <script type="text/javascript">
            function resetForm() {
                document.getElementById("form").reset();
            }
            function resetFormOnDemand(fields) {
                for (var i = 0; i < fields.length; i++) {
                    var field = document.getElementById(fields[i]);
                    field.value = "";
                }
            }
            function focusOn(idCampo) {
                document.getElementById(idCampo).focus();
            }
            function confirmar(texto, url) {
                if (confirm(texto)) {
                    window.location = url;
                }
            }

            $(document).ready(function () {
                $('#cnpj').mask('00.000.000/0000-00');
                $('#delivery_date').mask('00-00-0000');
                $('#validade').mask('00/00/0000');
                $('#number').mask('00000/0000');
                $('#valor, .valor').mask('000.000.000.000.000,00', {reverse: true});
                $('#form').submit(function submitForm() {
                    $(this).ajaxSubmit({
                        type: "POST",
                        url: $(this).attr("action"),
                        data: $(this).serialize(),
                        success: function (data) {
                            $("#resultado").html(data);
                        }
                    });
                    return false;
                });
            });
        </script>
    </body>
</html>