<?php

use App\Helpers\View;
use App\Config\Configurations as cfg;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Editando Registro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>altera/" method="post" id="form">
                            <?php if ($this->view->userLoggedIn['level'] != 'ADMINISTRADOR'): ?>
                                <input type="hidden" name="oms_id" value="<?= $this->view->result['oms_id'] ?>">
                                <input type="hidden" name="name" value="<?= $this->view->result['name'] ?>">
                                <input type="hidden" name="level" value="<?= $this->view->result['level'] ?>">
                            <?php endif; ?>
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Login</label>
                                        <input type="text"
                                               class="form-control"
                                               name="username"
                                               maxlength="20"
                                               placeholder="Login do Usuário - Username"
                                               id="username"
                                               value="<?= $this->view->result['username']; ?>"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password"
                                               class="form-control"
                                               name="password"
                                               maxlength="20"
                                               placeholder="Senha de Acesso - Password"
                                               id="password">
                                        <p class="help-block" style="color: red;">* Altere este campo apenas se for necessário.</p>
                                    </div>

                                    <?php if ($this->view->userLoggedIn['level'] == 'ADMINISTRADOR'): ?>
                                        <div class="form-group">
                                            <label>Nível de Acesso</label>
                                            <select name="level" id="level" class="form-control" required>
                                                <?php foreach (cfg::DEFAULT_USER_LEVELS as $level): ?>
                                                    <option value="<?= $level ?>" <?= View::isSelected($this->view->result['level'], $level)?>>
                                                        <?= $level; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    <?php endif; ?>
                                </div>

                                <div class="col-lg-6">
                                    <?php if ($this->view->userLoggedIn['level'] == 'ADMINISTRADOR'): ?>
                                        <div class="form-group">
                                            <label>Nome do Usuário</label>
                                            <input type="text"
                                                   class="form-control"
                                                   name="name"
                                                   maxlength="20"
                                                   placeholder="Nome do Usuário Responsável"
                                                   id="name"
                                                   value="<?= $this->view->result['name']; ?>"
                                                   required>
                                        </div>
                                    <?php endif; ?>

                                    <div class="form-group">
                                        <label>E-mail do Usuário</label>
                                        <input type="email"
                                               class="form-control"
                                               name="email"
                                               maxlength="100"
                                               placeholder="E-mail do Usuário Responsável"
                                               id="email"
                                               value="<?= $this->view->result['email']; ?>"
                                               required>
                                        <p class="help-block"></p>
                                    </div>

                                    <?php if ($this->view->userLoggedIn['level'] == 'ADMINISTRADOR'): ?>
                                        <div class="form-group">
                                            <label>Usuário ativo?</label>
                                            <select name="active"
                                                    id="active"
                                                    class="form-control"
                                                    required>
                                                <option value="yes" <?= $this->view->result['active'] == 'yes' ? 'selected' : '' ?>>
                                                    1 - Sim
                                                </option>
                                                <option value="no" <?= $this->view->result['active'] == 'no' ? 'selected' : '' ?>>
                                                    2 - Não
                                                </option>
                                            </select>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($this->view->userLoggedIn['level'] == 'ADMINISTRADOR'): ?>
                                        <div class="form-group">
                                            <label>OM</label>
                                            <select name="oms_id" id="oms_id" class="form-control" required>
                                                <?php foreach ($this->view->resultOm as $value): ?>
                                                    <option value="<?= $value['id']; ?>" <?= $this->view->result['oms_id'] == $value['id'] ? 'selected' : '' ?>>
                                                        <?= $value['naval_indicative']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    <?php endif; ?>
                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>