<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-lock"></i> <?=$this->view->title?></h3>
                </div>
                <div class="panel-body">
                    <div id="resultado"></div>
                    <form role="form" id="form" action="<?=$this->view->controller;?>autentica" method="post">
                        <div class="form-group input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </span>
                            <input type="text"
                                   name="username"
                                   id="username"
                                   class="form-control"
                                   placeholder="Login"
                                   autofocus
                                   required>
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-key"></i>
                            </span>
                            <input type="password"
                                   name="password"
                                   id="password"
                                   class="form-control"
                                   placeholder="Senha"
                                   required>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block">
                            <i class="fa fa-sign-in"></i> Entrar
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>