<?php

use App\Config\Configurations as cfg;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <input type="hidden" name="id">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Login</label>
                                        <input type="text"
                                               class="form-control"
                                               name="username"
                                               maxlength="20"
                                               placeholder="Login do Usuário - Username"
                                               id="username"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password"
                                               class="form-control"
                                               name="password"
                                               maxlength="20"
                                               placeholder="Senha de Acesso - Password"
                                               id="password"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Nível de Acesso</label>
                                        <select name="level"
                                                id="level"
                                                class="form-control"
                                                required>
                                            <?php foreach (cfg::DEFAULT_USER_LEVELS as $level): ?>
                                                <option value="<?= $level; ?>"><?= $level; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Nome do Usuário</label>
                                        <input type="text"
                                               class="form-control"
                                               name="name"
                                               maxlength="20"
                                               placeholder="Nome do Usuário Responsável"
                                               id="name"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>E-mail do Usuário</label>
                                        <input type="email"
                                               class="form-control"
                                               name="email"
                                               maxlength="100"
                                               placeholder="E-mail do Usuário Responsável"
                                               id="email"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>OM</label>
                                        <select name="oms_id"
                                                id="oms_id"
                                                class="form-control"
                                                required>
                                                    <?php foreach ($this->view->resultOm as $value): ?>
                                                <option value="<?= $value['id']; ?>">
                                                    <?= $value['naval_indicative']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>