<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Usuários Cadastrados</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus-circle"></i> Novo Registro
                </a>
                <div class="row">
                    <div class="col-md-6">
                        <?= $pagination; ?>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>OM</th>
                            <th>Nome</th>
                            <th>Nível</th>
                            <th>Ativo</th>
                            <th>Criado</th>
                            <th>Alterado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['naval_indicative']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td><?= $value['level']; ?></td>
                                <td><?= $value['active'] == 'yes' ? 'Sim' : 'Não'; ?></td>
                                <td><?= View::showDate($value['created_at']); ?></td>
                                <td><?= View::showDate($value['updated_at']); ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a
                                        onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                        class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>