<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Edição
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>alterandodata/idlista/<?= $this->view->idLista; ?>" method="post" id="form">
                            <input type="hidden" name="id" value="<?= $this->view->result['id']; ?>">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Data estipulada para entrega</label>
                                        <input type="text"
                                               name="data_entrega"
                                               id="data_entrega"
                                               placeholder="dd-mm-aaaa"
                                               class="form-control"
                                               maxlength="10"
                                               value="<?= $this->view->result['data_entrega']; ?>"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Alterar</button>
                                        <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->