<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><?= $this->view->title ?></h3>
            </div>
            <div class="col-lg-12">
                <h4>Lista de Fornecedores</h4>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>CNPJ</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['nome']; ?></td>
                                <td><?= $value['cnpj']; ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>formnaolicitado/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-shopping-cart"></i> Registrar Solicitação
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>naolicitado/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li><a href="<?= $this->view->controller; ?>naolicitado/pagina/<?= $value; ?>"><?= $value; ?></a></li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>naolicitado/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->