<?php
$busca = $this->getParametro('busca');
$busca = $busca ? '/busca/' . $busca : '';
$userNivel = $this->view->userLoggedIn['nivel'];

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Solicitações</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <div class="row">
                    <div class="col-md-7">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['previus'] . $busca; ?>" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <?php foreach ($this->view->btn['link'] as $value): ?>
                                    <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                        <a href="<?= $this->view->controller; ?>ver/pagina/<?= $value . $busca; ?>"><?= $value; ?></a>
                                    </li>
                                <?php endforeach; ?>
                                <li>
                                    <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['next'] . $busca; ?>" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>

                    <div class="col-lg-5">
                        <form action="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['current']; ?>" class="search-form">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nº Solicitação, Fornecedor ou Data (DD-MM-YYYY)">
                                <span class="input-group-btn">
                                    <button class="btn btn-default search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>


                <table class="table">
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>OM</th>
                            <th>Fornecedor</th>
                            <th>NF</th>
                            <th>Tipo</th>
                            <th>Status</th>
                            <th>Alteração</th>
                            <th>Entrega</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><small><?= $value['numero']; ?></small></td>
                                <td><small><?= $value['indicativo_naval']; ?></small></td>
                                <td><small><?= substr($value['fornecedor_nome'], 0, 17); ?> ... </small></td>
                                <td><?= $value['numero_nota_fiscal'] ?: ''; ?></td>
                                <td><?= !$value['nao_licitado'] ? '<i class="fa fa-group"></i> Lic.' : '<i class="fa fa-shopping-cart"></i> NL'; ?></td>
                                <td>
                                    <?= $value['status'] ?>
                                </td>
                                <td>
                                    <span class="label label-default">
                                        <?= date('d-m-Y', $value['updated_at']); ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="label label-info">
                                        <?= $value['data_entrega']; ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $value['id_lista']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-list"></i> Itens
                                    </a>

                                    <!-- BUTTONS -->
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'ENCARREGADO']) && $value['status'] == 'ABERTO'): ?>
                                        <a href="<?= $this->view->controller; ?>aprovar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-circle"></i> Aprovar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'APROVADO'): ?>
                                        <a href="<?= $this->view->controller; ?>processar/status/processado/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-cogs"></i> Processar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'PROCESSADO'): ?>
                                        <a href="<?= $this->view->controller; ?>processar/status/empenhado/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-file"></i> Empenhar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'EMPENHADO'): ?>
                                        <a href="<?= $this->view->controller; ?>processar/status/solicitado/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-bullhorn"></i> Solicitar
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($userNivel != 'CONTROLADOR' && $value['status'] == 'ABERTO'): ?>
                                        <a href="#"
                                           onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id_lista']; ?>')"
                                           class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($value['status'], ['RECEBIDO', 'SOLICITADO'])): ?>
                                        <a href="<?= $this->view->controller; ?>pdf/id/<?= $value['id']; ?>" class="btn btn-default btn-sm">
                                            <i class="fa fa-file-pdf-o"></i> PDF
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($userNivel != 'CONTROLADOR' && $value['status'] == 'SOLICITADO'): ?>
                                        <a href="<?= $this->view->controller; ?>receber/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-circle"></i> Receber
                                        </a>
                                    <?php endif; ?>
                                    <!-- END BUTTOS -->

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['previus'] . $busca; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                <a href="<?= $this->view->controller; ?>ver/pagina/<?= $value . $busca; ?>"><?= $value; ?></a>
                            </li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['next'] . $busca; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->