<?php
$busca = $this->getParametro('busca');
$busca = $busca ? '/busca/' . $busca : '';
$userNivel = $this->view->userLoggedIn['nivel'];

/**
 * This function build the string used in src attribute of action buttons
 * @param array $value The current solicitation
 * @param string $action The action to be executed
 * @return string The build string
 */
$buildUrlBtnAction = function (array $value, string $action = 'proximo'): string
{
    if (
        isset($value['status'], $value['nao_licitado']) && 
        $value['status'] === 'APROVADO' &&
        $value['nao_licitado'] === '1' &&
        $action !== 'anterior'
    ) {
        return $this->view->controller
            . 'processarnaolicitado/id/' . $value['id'];
    }

    return $this->view->controller
        . 'processar/acao/'
        . $action
        . '/status/'
        . $value['status']
        . '/id/'
        . $value['id'];
}

?>
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Solicitações</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <div class="row">
                    <div class="col-md-7">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['previous'] . $busca; ?>" aria-label="Previous" class="page-link">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <?php foreach ($this->view->btn['link'] as $value): ?>
                                    <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                        <a href="<?= $this->view->controller; ?>ver/pagina/<?= $value . $busca; ?>"  class="page-link"><?= $value; ?></a>
                                    </li>
                                <?php endforeach; ?>
                                <li>
                                    <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['next'] . $busca; ?>" aria-label="Next" class="page-link">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>

                    <div class="col-lg-5">
                        <form
                            action="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['current']; ?>"
                            class="search-form"
                            onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Nº Solicitação, Status ou Data (DD-MM-YYYY)">
                                <span class="input-group-btn">
                                    <button class="btn btn-default search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>OM</th>
                            <th>Fornecedor</th>
                            <th>NF</th>
                            <th>Tipo</th>
                            <th>Status</th>
                            <th>Alteração</th>
                            <th>Entrega</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><small><?= $value['numero']; ?></small></td>
                                <td><small><?= $value['indicativo_naval']; ?></small></td>
                                <td><small><?= count($value['fornecedor_nome']) > 17 ? substr($value['fornecedor_nome'], 0, 17) . '..' : $value['fornecedor_nome']; ?></small></td>
                                <td><?= $value['numero_nota_fiscal'] ?: ''; ?></td>
                                <td>
                                    <?php if ($value['nao_licitado'] === '0') : ?>
                                        <i class="fa fa-group"></i> LIC
                                    <?php else : ?>
                                        <i class="fa fa-shopping-cart"></i> NL
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?= $value['status'] ?>
                                </td>
                                <td>
                                    <span class="label label-default">
                                        <?= date('d-m-Y', $value['updated_at']); ?>
                                    </span>
                                </td>
                                <td>
                                    <span class="label label-info">
                                        <?= $value['data_entrega']; ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $value['id_lista']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-list"></i> Itens
                                    </a>

                                    <!-- BUTTONS -->
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'ENCARREGADO']) && $value['status'] == 'ABERTO'): ?>
                                        <a href="<?= $this->view->controller; ?>aprovar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-circle"></i> Aprovar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'APROVADO'): ?>
                                        <a href="<?= $buildUrlBtnAction($value); ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-cogs"></i> Processar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'PROCESSADO'): ?>
                                        <a href="<?= $buildUrlBtnAction($value) ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-file"></i> Empenhar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'EMPENHADO'): ?>
                                        <a href="<?= $buildUrlBtnAction($value) ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-bullhorn"></i> Solicitar
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'RECEBIDO'): ?>
                                        <a href="<?= $buildUrlBtnAction($value) ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-file"></i> Receber NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'NF-ENTREGUE'): ?>
                                        <a href="<?= $buildUrlBtnAction($value) ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-square-o"></i> Enc. NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && $value['status'] == 'NF-FINANCAS'): ?>
                                        <a href="<?= $buildUrlBtnAction($value) ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-dollar"></i> Pagar NF
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($userNivel != 'CONTROLADOR' && $value['status'] == 'ABERTO'): ?>
                                        <a
                                           onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id_lista']; ?>')"
                                           class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($value['status'], ['SOLICITADO', 'RECEBIDO', 'NF-ENTREGUE', 'NF-FINANCAS', 'NF-PAGA'])): ?>
                                        <a href="<?= $this->view->controller; ?>pdf/id/<?= $value['id']; ?>" class="btn btn-default btn-sm">
                                            <i class="fa fa-file-pdf-o"></i> PDF
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($userNivel != 'CONTROLADOR' && $value['status'] == 'SOLICITADO'): ?>
                                        <a href="<?= $this->view->controller; ?>receber/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-check-circle"></i> Receber
                                        </a>
                                    <?php endif; ?>
                                    <?php if (in_array($userNivel, ['ADMINISTRADOR', 'CONTROLADOR']) && !in_array($value['status'], ['ABERTO', 'DESMEMBRADO'])): ?>
                                        <a href="<?= $buildUrlBtnAction($value, 'anterior') ?>" class="btn btn-warning btn-sm">
                                            <i class="fa fa-rotate-left"></i>
                                        </a>
                                    <?php endif; ?>
                                    <!-- END BUTTOS -->

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['previous'] . $busca; ?>" aria-label="Previous" class="page-link">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                <a href="<?= $this->view->controller; ?>ver/pagina/<?= $value . $busca; ?>"  class="page-link"><?= $value; ?></a>
                            </li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['next'] . $busca; ?>" aria-label="Next" class="page-link">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>