<?php

use App\Helpers\Pagination;

$pagination = Pagination::make($this, function ($btn, $controllerName) {
        return [
            'previous' => "{$controllerName}novo/pagina/{$btn['previous']}",
            'next' => "{$controllerName}novo/pagina/{$btn['next']}",
            'current' => "{$controllerName}novo/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Licitações Disponíveis</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?>

                <div class="row">
                    <div class="col-md-7">
                        <?= $pagination; ?>
                    </div>

                    <div class="col-lg-5">
                        <form
                            action="<?= $this->view->controller; ?>itensLicitados"
                            class="search-form"
                            onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Buscar produtos licitados...">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>

                <table class="table">
                    <thead>
                        <tr>
                            <th>Numero</th>
                            <th>Descrição</th>
                            <th>UASG</th>
                            <th>Órgão</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr class="table-licitacao" data-idLista="<?= $value['id_lista']; ?>">
                                <td><?= $value['numero']; ?></td>
                                <td><?= $value['descricao']; ?></td>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['nome_uasg']; ?></td>
                                <td>
                                    <span class="label label-danger">
                                        <?= date('d-m-Y', $value['validade']); ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var formAction = $('.search-form').attr('action');
        if (searchValue && formAction) {
            window.location = formAction + '/busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    });
    $('.table-licitacao').click(function link() {
        var idLista = $(this).attr('data-idLista');
        window.location = "<?= $this->view->controller; ?>fornecedor/idlista/"+idLista;
    });
</script>
<style>
    .table-licitacao:hover {
        cursor: pointer;
        background-color: #ccc;
    }
</style>