<?php

use App\Helpers\Pagination;
use App\Helpers\View;
use App\Config\Configurations as cfg;
use App\Helpers\Utils;

$idlista = $this->view->idlista;
$relativePathUploadFiles = 'arquivos' . cfg::DS . $this->view->resultSolicitacao['number'] . cfg::DS;
$fullPathUploadFiles = getcwd() . cfg::DS . $relativePathUploadFiles;

$pagination = Pagination::make($this, function ($btn, $controllerName) use ($idlista) {
        return [
            'previous' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['previous']}",
            'next' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/{$btn['next']}",
            'current' => "{$controllerName}detalhar/idlista/{$idlista}/pagina/" . Pagination::CURRENT_PAGE
        ];
    });

?>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Informações da Pré-SOLEMP</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="ug" class="col-form-label">UG:</label>
                            <input type="text" class="form-control" id="ug">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="ptres" class="col-form-label">PTRES:</label>
                            <input type="text" class="form-control" id="ptres">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="ai" class="col-form-label">AI:</label>
                            <input type="text" class="form-control" id="ai">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="do" class="col-form-label">DO:</label>
                            <input type="text" class="form-control" id="do">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="bi" class="col-form-label">BI:</label>
                            <input type="text" class="form-control" id="bi">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="fr" class="col-form-label">FR:</label>
                            <input type="text" class="form-control" id="fr">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="nd" class="col-form-label">ND:</label>
                            <input type="text" class="form-control" id="nd">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="plano_contas" class="col-form-label">Plano de Contas:</label>
                            <input type="text" class="form-control" id="plano_contas">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="tipo_empenho" class="col-form-label">Tipo de Empenho:</label>
                            <input type="text" class="form-control" id="tipo_empenho">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="modalidade" class="col-form-label">Modalidade:</label>
                            <input type="text" class="form-control" id="modalidade">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="classificacao_item" class="col-form-label">Classificação itens:</label>
                            <input type="text" class="form-control" id="classificacao_item">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="centro_custo" class="col-form-label">Centro de Custo:</label>
                            <input type="text" class="form-control" id="centro_custo">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="finalidade" class="col-form-label">Finalidade:</label>
                            <textarea class="form-control" id="finalidade"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success btn-confirm" data-dismiss="modal">Confirmar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalSuppliersDetails" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Informações do Fornecedor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <strong>
                    Nome:
                </strong>
                <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                <br>
                <strong>
                    CNPJ:
                </strong>
                <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                <br>
                <strong>
                    Dados:
                </strong>
                <br>
                <?= $this->view->resultSolicitacao['suppliers_details']; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Itens da Solicitação</h5>
                <?php if (isset($this->view->resultLicitacao['number'])): ?>
                    <div class="alert alert-info" role="alert">
                        Licitação: <strong><?= $this->view->resultLicitacao['number']; ?></strong><br>
                        Órgão: <strong><?= $this->view->resultLicitacao['uasg']; ?> - <?= $this->view->resultLicitacao['uasg_name']; ?></strong><br>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                        </strong>
                        (<a href="#"
                            class="text-danger"
                            data-toggle="modal"
                            data-target="#modalSuppliersDetails">
                            mais detalhes
                        </a>)
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['number']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                        <br>
                        Data para entrega: <strong><?= View::humanDate($this->view->resultSolicitacao['delivery_date']); ?></strong>
                        <?php
                        if ($this->view->resultSolicitacao['status'] === 'ABERTO'):
                            $solicitacaoId = $this->view->resultSolicitacao['id'];
                            $url = $this->view->controller . 'alterardata/id/' . $solicitacaoId;

                            ?>
                            (<a href="<?= $url; ?>"
                                class="text-danger">
                                Alterar <i class="fa fa-edit"></i>
                            </a>)
                        <?php endif; ?>
                    </div>
                <?php else: ?>
                    <div class="alert alert-info" role="alert">
                        <h4>NÃO LICITADO</h4>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['suppliers_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['suppliers_name']; ?>
                        </strong>
                        (<a href="#"
                            class="text-danger"
                            data-toggle="modal"
                            data-target="#modalSuppliersDetails">
                            mais detalhes
                        </a>)
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['number']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                        <br>
                        Data para entrega: <strong><?= View::humanDate($this->view->resultSolicitacao['delivery_date']); ?></strong>
                        <?php
                        if ($this->view->resultSolicitacao['status'] === 'ABERTO'):
                            $solicitacaoId = $this->view->resultSolicitacao['id'];
                            $url = $this->view->controller . 'alterardata/id/' . $solicitacaoId;

                            ?>
                            (<a href="<?= $url; ?>"
                                class="text-danger">
                                Alterar <i class="fa fa-edit"></i>
                            </a>)
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <a href="<?= $this->view->controller; ?>" class="btn btn-warning pull-right">
                    <i class="fa fa-arrow-left"></i> Voltar
                </a>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO', 'NORMAL']) && $this->view->resultSolicitacao['status'] == 'ABERTO' && !isset($this->view->resultLicitacao['number'])): ?>
                    <a href="<?= $this->view->controller; ?>adicionararquivo/idlista/<?= $this->view->idlista; ?>" class="btn btn-info pull-right" style="margin-right: 10px;">
                        <i class="fa fa-file"></i> Adicionar arquivo
                    </a>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'CONTROLADOR']) && $this->view->resultSolicitacao['status'] == 'APROVADO'): ?>
                    <a href="<?= $this->view->controller; ?>processar/acao/proximo/status/APROVADO/id/<?= $this->view->idlista; ?>" class="btn btn-success pull-right" style="margin-right: 10px;">
                        <i class="fa fa-cogs"></i> Processar
                    </a>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'CONTROLADOR']) && !in_array($this->view->resultSolicitacao['status'], ['ABERTO', 'APROVADO'])): ?>
                    <button type="button" class="btn btn-primary pull-right btn-pre-solemp" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-file-text"></i> Gerar Pré-SOLEMP
                    </button>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['level'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->resultSolicitacao['status'] == 'ABERTO'): ?>
                    <div class="row">
                        <div class="col-md-6">
                            <a href="<?= $this->view->controller ?>aprovar/id/<?= $this->view->resultSolicitacao['id'] ?>" class="btn btn-success">
                                <i class="fa fa-check"></i> Aprovar Solicitação
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (!isset($this->view->resultLicitacao['number'])): ?>
                    <table class="table table-hover table-bordered" style="margin-top: 10px;">
                        <thead>
                            <tr>
                                <th colspan="2">
                                    Arquivos
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach (View::listFilesPdf($fullPathUploadFiles) as $file): ?>
                                <tr>
                                    <td>
                                        <a href="<?= $relativePathUploadFiles . $file ?>" target="_blank">
                                            Arquivo <?= $file; ?>
                                        </a>
                                    </td>
                                    <td width="8%">
                                        <?php if ($this->view->resultSolicitacao['status'] == 'ABERTO'): ?>
                                            <a
                                                onclick="confirmar('Deseja REMOVER este arquivo?', '<?= $this->view->controller; ?>eliminararquivo/file/<?= $file; ?>/idlista/<?= $this->view->idlista; ?>')"
                                                class="btn btn-danger btn-sm">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Solicitado</th>
                            <th>Recebido</th>
                            <th>Valor (R$)</th>
                            <th>UF</th>
                            <th>Nome</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['number'] ?: ''; ?></td>
                                <td><?= intval($value['quantity']); ?></td>
                                <td><?= intval($value['delivered']); ?></td>
                                <td><?= Utils::floatToMoney($value['value']); ?></td>
                                <td><?= $value['uf']; ?></td>
                                <td><?= $value['name']; ?></td>
                                <td>
                                    <?php if ($this->view->userLoggedIn['level'] != 'CONTROLADOR' && $this->view->resultSolicitacao['status'] == 'ABERTO') : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a
                                            onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminaritem/id/<?= $value['id']; ?>/idlista/<?= $this->view->idlista; ?>')"
                                            class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
<style>
    .btn-pre-solemp {
        margin-left: 10px;
        margin-right: 10px;
    }
</style>
<script>
    $(document).ready(function () {
        $('.btn-confirm').click(function () {
            var ug = $('#ug').val();
            var ptres = $('#ptres').val();
            var ai = $('#ai').val();
            var do_ = $('#do').val();
            var bi = $('#bi').val();
            var fr = $('#fr').val();
            var nd = $('#nd').val();
            var plano_contas = $('#plano_contas').val();
            var tipo_empenho = $('#tipo_empenho').val();
            var classificacao_item = $('#classificacao_item').val();
            var centro_custo = $('#centro_custo').val();
            var modalidade = $('#modalidade').val();
            var finalidade = $('#finalidade').val();
            var idlista = <?= $idlista; ?>;
            var valuesPresolemp = {
                ug: ug,
                ptres: ptres,
                ai: ai,
                do_: do_,
                bi: bi,
                fr: fr,
                nd: nd,
                plano_contas: plano_contas,
                tipo_empenho: tipo_empenho,
                modalidade: modalidade,
                finalidade: finalidade,
                classificacao_item: classificacao_item,
                centro_custo: centro_custo,
                usuario: '<?= "{$this->view->userLoggedIn['name']} - {$this->view->userLoggedIn['email']}"; ?>'
            };

            window.localStorage.clear();
            window.localStorage.setItem('presolemp_' + idlista, JSON.stringify(valuesPresolemp));
            window.open('<?= $this->view->controller; ?>presolemp/idlista/<?= $idlista; ?>', '_blank');
                    });
                });
</script>