<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Itens da Solicitação</h3>
                <?php if (isset($this->view->resultLicitacao['numero'])): ?>
                    <div class="alert alert-info" role="alert">
                        Licitação: <strong><?= $this->view->resultLicitacao['numero']; ?></strong><br>
                        Órgão: <strong><?= $this->view->resultLicitacao['uasg']; ?> - <?= $this->view->resultLicitacao['nome_uasg']; ?></strong><br>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['fornecedor_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['fornecedor_nome']; ?>
                        </strong>
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['numero']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                        <br>
                        Data para entrega: <strong><?= $this->view->resultSolicitacao['data_entrega']; ?></strong>
                        <?php
                        if ($this->view->resultSolicitacao['status'] === 'ABERTO'):
                            $solicitacaoId = $this->view->resultSolicitacao['id'];
                            $idLista = $this->view->resultSolicitacao['id_lista'];
                            $url = $this->view->controller . 'alterardata/id/' . $solicitacaoId . '/idlista/' . $idLista;

                            ?>
                            (<a href="<?= $url; ?>"
                                class="text-danger">
                                Alterar <i class="fa fa-edit"></i>
                            </a>)
                        <?php endif; ?>
                    </div>
                <?php else: ?>
                    <div class="alert alert-info" role="alert">
                        <h4>NÃO LICITADO</h4>
                        Fornecedor:
                        <strong>
                            <?= $this->view->resultSolicitacao['fornecedor_cnpj']; ?>
                            - <?= $this->view->resultSolicitacao['fornecedor_nome']; ?>
                        </strong>
                        <br>
                        Solicitação:
                        <strong>
                            <?= $this->view->resultSolicitacao['numero']; ?>
                            - <?= $this->view->resultSolicitacao['status']; ?>
                        </strong>
                        <br>
                        <?php if ($this->view->resultSolicitacao['lista_desmembramento']) : ?>
                            Desmembrado nas solicitações:
                            <strong>
                                <?= $this->view->resultSolicitacao['lista_desmembramento']; ?>
                            </strong>
                            <br>
                        <?php endif; ?>
                        Data para entrega: <strong><?= $this->view->resultSolicitacao['data_entrega']; ?></strong>
                        <?php
                        if ($this->view->resultSolicitacao['status'] === 'ABERTO'):
                            $solicitacaoId = $this->view->resultSolicitacao['id'];
                            $idLista = $this->view->resultSolicitacao['id_lista'];
                            $url = $this->view->controller . 'alterardata/id/' . $solicitacaoId . '/idlista/' . $idLista;

                            ?>
                            (<a href="<?= $url; ?>"
                                class="text-danger">
                                Alterar <i class="fa fa-edit"></i>
                            </a>)
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if (in_array($this->view->userLoggedIn['nivel'], ['ADMINISTRADOR', 'ENCARREGADO']) && $this->view->resultSolicitacao['status'] == 'ABERTO'): ?>
                    <div class="row">
                        <div class="col-md-6">
                            <a href="<?= $this->view->controller ?>aprovar/id/<?= $this->view->resultSolicitacao['id'] ?>" class="btn btn-success">
                                <i class="fa fa-check"></i> Aprovar Solicitação
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="row" style="margin-bottom: 10px; margin-top: 10px;">
                    <div class="col-md-12">
                        <i class="fa fa-list"></i> <?= $this->view->title; ?>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Solicitado</th>
                            <th>Recebido</th>
                            <th>Valor (R$)</th>
                            <th>UF</th>
                            <th>Nome</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['item_numero'] ?: ''; ?></td>
                                <td><?= $value['item_quantidade']; ?></td>
                                <td><?= $value['item_quantidade_atendida']; ?></td>
                                <td><?= number_format($value['item_valor'], 2, ',', '.'); ?></td>
                                <td><?= $value['item_uf']; ?></td>
                                <td><?= $value['item_nome']; ?></td>
                                <td>
                                    <?php if ($this->view->userLoggedIn['nivel'] != 'CONTROLADOR' && $this->view->resultSolicitacao['status'] == 'ABERTO') : ?>
                                        <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>/idlista/<?= $this->view->idLista; ?>" class="btn btn-success">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <a
                                           onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminaritem/id/<?= $value['id']; ?>/idlista/<?= $this->view->idLista; ?>')"
                                           class="btn btn-danger">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['previous']; ?>" aria-label="Previous" class="page-link">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li class="<?= $this->view->btn['current'] == $value ? 'active' : '' ?>">
                                <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $value; ?>">
                                    <?= $value; ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>detalhar/idlista/<?= $this->view->idLista; ?>/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next" class="page-link">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>