<?php

use App\Helpers\View;

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <?php if ($this->view->result) { ?>
                    <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                    <div class="row">
                        <div class="col-md-7"></div>
                        <div class="col-lg-5">
                            <form
                                action="<?= $this->view->controller; ?>itensLicitados"
                                class="search-form"
                                onsubmit="return false">
                                <div class="input-group search-input-box">
                                    <input type="text" class="form-control search-input" placeholder="Buscar itens licitados...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-secondary search-button" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Licitação</th>
                                <th>Fornecedor</th>
                                <th width="45%">Item</th>
                                <th width="15%"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->view->result as $value): ?>
                                <tr>
                                    <td><?= $value['number']; ?></td>
                                    <td><?= $value['name']; ?></td>
                                    <td><?= View::highlight(strtoupper($value['produtoNome']), strtoupper($this->view->busca)) ?></td>
                                    <td>
                                        <a href="<?= $this->view->controller; ?>item/fornecedor/<?= $value['suppliers_id']; ?>/idlista/<?= $value['id_lista']; ?>" class="btn btn-success btn-sm">
                                            <i class="fa fa-edit"></i> Ir para Fornecedor
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php } else { ?>
                    <div class="col-lg-12">
                        <form
                            action="<?= $this->view->controller; ?>itensLicitados"
                            class="search-form"
                            onsubmit="return false">
                            <div class="input-group search-input-box">
                                <input type="text" class="form-control search-input" placeholder="Buscar produtos licitados...">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary search-button" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <br>
                    <div class="alert alert-warning">
                        <i class="fa fa-warning"></i> Nenhum resultado encontrado para <b><?= $this->view->busca ?></b>. Tente outra busca! <br />
                        <br/>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script>
    $('.search-button').click(function btnSearch() {
        var searchInput = $('.search-input');
        var searchValue = searchInput.val();
        var formAction = $('.search-form').attr('action');
        if (searchValue && formAction) {
            window.location = formAction + '/busca/' + searchValue;
        } else {
            searchInput.focus();
        }
    });
</script>