<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Fornecedor(es) desta licitação</h5>
                <div class="alert alert-info">
                    Licitação: <?= $this->view->result[0]['number']; ?><br />
                    Descrição: <?= $this->view->result[0]['description']; ?><br />
                    UASG: <?= $this->view->result[0]['uasg']; ?><br />
                    Órgão: <?= $this->view->result[0]['uasg_name']; ?><br />
                </div>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Fornecedor</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['name']; ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>item/fornecedor/<?= $value['suppliers_id']; ?>/idlista/<?= $value['biddings_id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i> Registrar Solicitação
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>