<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <form action="<?= $this->view->controller; ?>registranaolicitado" method="post" id="form">
            <div class="row">
                <div class="col-lg-12">
                    <h3></h3>
                    <div id="resultado"></div>
                    <input type="hidden" name="id_licitacao" value="0">
                    <input type="hidden" name="nao_licitado" value="1">
                    <input type="hidden" name="numero_nota_fiscal" value="S/N">
                    <input type="hidden" name="observacao">
                    <div class="col-lg-6">
                        <button class="btn btn-info">
                            <i class="fa fa-check"></i> Confirmar Registro
                        </button>
                    </div>
                    <div class="col-lg-6">
                        <a class="btn btn-success pull-right" id="add">
                            <i class="fa fa-plus-circle"></i> Adicionar Campo
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4" style="margin-top: 10px;">
                    <label>Data estipulada para entrega:</label>
                    <input type="text"
                           name="data_entrega"
                           id="data_entrega"
                           class="form-control"
                           placeholder="Data no formato DD-MM-AAAA"
                           required
                           maxlength="10">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="8%">Quantidade</th>
                                <th width="8%">UF</th>
                                <th>Descrição</th>
                                <th width="8%"></th>
                            </tr>
                        </thead>
                        <tbody  id="lista">
                            <tr>
                                <td>
                                    <input type="hidden" name="id[]" value="">
                                    <input type="text"
                                           name="quantidade[]"
                                           id="quantidade"
                                           class="form-control"
                                           required
                                           maxlength="10">
                                </td>
                                <td>
                                    <input type="text"
                                           name="uf[]"
                                           id="uf"
                                           class="form-control"
                                           required
                                           maxlength="5">
                                </td>
                                <td>
                                    <input type="text"
                                           name="nome[]"
                                           id="nome"
                                           class="form-control"
                                           required
                                           maxlength="50">
                                </td>
                                <td></td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
$(document).ready(function () {
    var x = 1;
    $('#add').click(function (e) {
        e.preventDefault();
        $('#lista').append('\
                    <tr class="remove' + x + '">\
                        <td>\
                            <input type="hidden"\
                                   name="id[]"\
                                   value="">\
                            <input type="text"\
                                   name="quantidade[]"\
                                   id="quantidade"\
                                   class="form-control"\
                                   required\
                                   maxlength="10">\
                        </td>\
                        <td><input type="text"\
                                   name="uf[]"\
                                   id="uf"\
                                   class="form-control"\
                                   required\
                                   maxlength="5"></td>\
                        <td><input type="text"\
                                   name="nome[]"\
                                   id="nome"\
                                   class="form-control"\
                                   required\
                                   maxlength="50"></td>\
                        <td><a href="#" class="remove btn btn-danger" id="remove' + x + '">\
                            <i class="fa fa-times"></i>\
                        </td>\
                    </tr>\
            ');
        x++;
    });

    $('#lista').on("click", ".remove", function (e) {
        e.preventDefault();
        var tr = $(this).attr('id');
        $('#lista tr.' + tr).remove();
        x--;
    });
});
</script>