<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3></h3>
                <div id="resultado"></div>
                <?php if (isset($this->view->result[0])): ?>
                    <form action="<?= $this->view->controller; ?>registrarrecebimento/id/<?= $this->view->result[0]['solicitacao_id']; ?>" method="post" id="form">
                        <input type="hidden" name="id_licitacao" value="<?= $this->view->result[0]['id_licitacao'] ?>">
                        <input type="hidden" name="nao_licitado" value="<?= $this->view->result[0]['nao_licitado'] ?>">
                        <input type="hidden" name="data_entrega" value="<?= date("d-m-Y", time()); ?>">
                        <button class="btn btn-success" id='btn_enviar'>
                            <i class="fa fa-check"></i> Confirmar Recebimento
                        </button>
                        <div class="row" style="padding-top: 10px;">
                            <div class="col-lg-4" id="numero_nota_fiscal_container">
                                <label>Número da Nota Fiscal: </label>
                                <input type="text" name="numero_nota_fiscal"
                                       id="numero_nota_fiscal"
                                       class="form-control"
                                       maxlength="20"
                                       placeholder="Número da nota fiscal"
                                       autofocus>
                            </div>
                            <?php if (isset($this->view->result[0]['nao_licitado']) && $this->view->result[0]['nao_licitado'] !== '1'): ?>
                                <div class="col-lg-4" id="nota">
                                    <label>Avaliação da entrega: </label><br>
                                    <input type="radio" name="nota" value="1">
                                    <span class="label label-danger">
                                        1
                                    </span>&nbsp;
                                    <input type="radio" name="nota" value="2">
                                    <span class="label label-default">
                                        2
                                    </span>&nbsp;
                                    <input type="radio" name="nota" value="3" checked>
                                    <span class="label label-warning">
                                        3
                                    </span>&nbsp;
                                    <input type="radio" name="nota" value="4">
                                    <span class="label label-success">
                                        4
                                    </span>&nbsp;
                                    <input type="radio" name="nota" value="5">
                                    <span class="label label-info">
                                        5
                                    </span>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="row" style="padding-top: 10px; margin-bottom: 20px;">
                            <div class="col-lg-4" id="observacao">
                                <label>Observação: </label>
                                <textarea name="observacao"
                                          placeholder="Observações"
                                          class="form-control"></textarea>
                            </div>
                            <?php if (isset($this->view->result[0]['nao_licitado']) && $this->view->result[0]['nao_licitado'] !== '1'): ?>
                            <div class="col-lg-6" id="legenda">
                                <label>Legenda:</label><br>
                                <span class="label label-danger" style="font-size: 14px !important;">1 - Muito insatisfeito</span> à
                                <span class="label label-info" style="font-size: 14px !important;">5 - Muito satisfeito</span>
                            </div>
                            <?php endif; ?>
                        </div>
                        <table class="table" id='tabela_result'>
                            <thead>
                                <tr>
                                    <th width="8%">Entregue</th>
                                    <th width="8%">Solicitado</th>
                                    <th>Item</th>
                                    <th>Valor Unitário</th>
                                    <th>UF</th>
                                    <th>Nome</th>
                                    <th>Fornecedor</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->view->result as $value): ?>
                                    <tr>
                                        <td>
                                            <input type="hidden"
                                                   name="id[]"
                                                   value="<?= $value['id']; ?>">
                                            <input type="hidden"
                                                   name="uf[]"
                                                   value="<?= $value['item_uf']; ?>">
                                            <input type="hidden"
                                                   name="valor[]"
                                                   value="<?= $value['item_valor']; ?>">
                                            <input type="hidden"
                                                   name="fornecedor[]"
                                                   value="">
                                            <input type="hidden"
                                                   name="nome[]"
                                                   value="---">
                                            <input type="text"
                                                   name="quantidade[]"
                                                   id="quantidade"
                                                   value="<?= $value['item_quantidade']; ?>"
                                                   class="form-control">
                                        </td>
                                        <td><?= $value['item_quantidade']; ?></td>
                                        <td><?= $value['item_numero']; ?></td>
                                        <td>R$ <?= number_format($value['item_valor'], 2, ",", "."); ?></td>
                                        <td><?= $value['item_uf']; ?></td>
                                        <td><?= $value['item_nome']; ?></td>
                                        <td>
                                            <span class="label label-default">
                                                <?= $value['fornecedor_nome']; ?>
                                            </span>
                                            <br>
                                            <span class="label label-danger">
                                                <?= $value['cnpj']; ?>
                                            </span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </form>

                <?php else: ?>
                    <div class="alert alert-info">
                        Esta solicitação já foi recebida.
                    </div>
                <?php endif; ?>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<script>
    function mostrar(id) {
        $("#" + id).show();
    }
    function ocultar(id) {
        $("#" + id).hide();
    }
</script>