<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Licitações Disponíveis</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Numero</th>
                            <th>UASG</th>
                            <th>Órgão</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['numero']; ?></td>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['nome_uasg']; ?></td>
                                <td>
                                    <span class="label label-danger">    
                                        <?= date('d-m-Y', $value['validade']); ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>fornecedor/idlista/<?= $value['id_lista']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i> Registrar Solicitação
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>novo/pagina/<?= $this->view->btn['previous']; ?>" aria-label="Previous" class="page-link">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li><a class="page-link" href="<?= $this->view->controller; ?>novo/pagina/<?= $value; ?>"><?= $value; ?></a></li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>novo/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next" class="page-link">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>