<div id="page-wrapper">
    <div class="container-fluid">
        <form action="<?= $this->view->controller; ?>registranaolicitado" method="post" id="form" enctype="multipart/form-data">
            <div class="row">
                <input type="hidden" name="biddings_id" value="S/N">
                <input type="hidden" name="invoice" value="S/N">
                <input type="hidden" name="observation">
                <div class="col-md-12">
                    <div id="resultado"></div>
                </div>
                <div class="col-lg-6">
                    <button class="btn btn-success">
                        <i class="fa fa-check"></i> Confirmar Registro
                    </button>
                </div>
                <div class="col-lg-6">
                    <a class="btn btn-info pull-right add" id="add-row">
                        <i class="fa fa-plus-circle"></i> Adicionar Item
                    </a>
                    <a class="btn btn-warning pull-right add" id="add-file">
                        <i class="fa fa-file"></i> Adicionar Arquivo
                    </a>
                </div>
            </div>
            <div class="row" style="margin-top: 10px; margin-bottom: 20px;">
                <div class="col-md-6">
                    <label>Data estipulada para entrega:</label>
                    <input type="text"
                           name="delivery_date"
                           id="delivery_date"
                           class="form-control"
                           data-mask="00-00-0000"
                           data-mask-reverse="true"
                           placeholder="Data no formato DD-MM-AAAA"
                           required
                           maxlength="10">
                </div>
                <div class="col-md-6">
                    <label>Fornecedor:</label>
                    <select name="suppliers_id" class="form-control" required>
                        <option value="">---</option>
                        <?php foreach ($this->view->resultFornecedor as $value) : ?>
                            <option value="<?= $value['id']; ?>"><?= $value['cnpj']; ?> - <?= $value['name']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    Arquivo(s) necessários para solicitação (Somente PDF)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="file-list">
                            <tr>
                                <td>
                                    <input type="file" name="files[]" accept="application/pdf" required>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="8%">Quantidade</th>
                                <th width="8%">UF</th>
                                <th width="15%">Valor</th>
                                <th>Descrição</th>
                                <th width="8%"></th>
                            </tr>
                        </thead>
                        <tbody id="row-list">
                            <tr>
                                <td>
                                    <input type="text"
                                           name="quantity[]"
                                           class="form-control"
                                           required
                                           maxlength="10">
                                </td>
                                <td>
                                    <input type="text"
                                           name="uf[]"
                                           class="form-control"
                                           required
                                           maxlength="5">
                                </td>
                                <td>
                                    <input type="text"
                                           name="value[]"
                                           class="form-control"
                                           data-mask="000.000.000,00"
                                           data-mask-reverse="true"
                                           required>
                                </td>
                                <td>
                                    <input type="text"
                                           name="name[]"
                                           class="form-control"
                                           required
                                           maxlength="50">
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="hide">
    <table>
        <tr class="table-values remove--X-">
            <td>
                <input type="text" name="quantity[]" class="form-control" maxlength="10" required="">
            </td>
            <td>
                <input type="text" name="uf[]" class="form-control" maxlength="5" required="">
            </td>
            <td>
                <input type="text"
                       name="value[]"
                       class="form-control valor"
                       required="">
            </td>
            <td>
                <input type="text" name="name[]" class="form-control" maxlength="50" required="">
            </td>
            <td>
                <a class="remove btn btn-danger btn-sm" data-reference="-X-">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
        <tr class="table-files remove--X-">
            <td>
                <input type="file" name="files[]" required="" accept="application/pdf">
            </td>
            <td>
                <a class="remove btn btn-danger btn-sm" data-reference="-X-">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
    </table>
</div>
<script>
    $(document).ready(function () {
        var xRow = 1;
        var xFile = 1;

        var getTemplate = function getTemplate(className, reference) {
            return $('tr.' + className + '.remove--X-')
                    .get(0)
                    .outerHTML
                    .replace('table-values ', '')
                    .replace(/-X-/g, reference);
        };
        /**
         * Add a new row into table values
         */
        $('#add-row').click(function addRowItem(event) {
            event.preventDefault();
            var template = getTemplate('table-values', xRow);
            $('#row-list').append(template);
            xRow++;
        });
        /**
         * Add a new row into table files
         */
        $('#add-file').click(function addFileItem(event) {
            event.preventDefault();
            var template = getTemplate('table-files', xFile);
            $('#file-list').append(template);
            xFile++;
        });
        /**
         * Remove a row from table values
         */
        $('#row-list').on("click", ".remove", function removeRowItem(event) {
            event.preventDefault();
            var reference = $(this).attr('data-reference');
            $('#row-list tr.remove-' + reference).remove();
        });
        /**
         * Remove a row from table values
         */
        $('#file-list').on("click", ".remove", function removeFileItem(event) {
            event.preventDefault();
            var reference = $(this).attr('data-reference');
            $('#file-list tr.remove-' + reference).remove();
        });
    });
</script>
<style>
    .add {
        color: #fff !important;
        margin-right: 10px;
    }
</style>