<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Fornecedor(es) desta licitação</h3>
                <div class="alert alert-info">
                    Licitação: <?= $this->view->result[0]['numero']; ?><br />
                    UASG: <?= $this->view->result[0]['uasg']; ?><br />
                    Órgão: <?= $this->view->result[0]['nome_uasg']; ?><br />
                </div>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Fornecedor</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['nome']; ?></td>
                                <td>
                                    <a href="<?= $this->view->controller; ?>item/fornecedor/<?= $value['fornecedor_id']; ?>/idlista/<?= $value['id_lista']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i> Registrar Solicitação
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
