<?php

use App\Helpers\View;
use App\Config\Configurations as cfg;

setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set(cfg::TIMEZONE);

$mes = function($data) {
    return 'aquii';
};

// valida para que as informações sejam geradas apenas quando o status for igual a APROVADO
if (!isset($this->view->result[0])) {
    die("<i class='fa fa-info-circle'></i> A papeleta não pode ser gerada..");
}

?>
<table class="table-print">
    <tr>
        <td colspan="3" class="cabecalho">
            MARINHA DO BRASIL<br />
            <?= ($this->view->result[0]['oms_name']); ?><br />
            DIVISÃO DE MUNICIAMENTO
        </td>
    </tr>
    <tr>
        <td colspan="2" class="agente-fiscal">
            <div class="content-assinatura">
                <?= ($this->view->result[0]['fiscal_agent']); ?><br />
                <?= ($this->view->result[0]['fiscal_agent_graduation']); ?><br />
                Agente Fiscal
            </div>
        </td>
        <td class="number">
            Solicitação Nº
            <strong>
                <?= ($this->view->result[0]['requests_number']); ?>
            </strong>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="fornecedor">
            FORNECEDOR: <?= ($this->view->result[0]['cnpj']); ?> - <?= ($this->view->result[0]['suppliers_name']); ?>
        </td>
        <td class="tipo-documento">
            <?=
            $this->view->result[0]['biddings_id'] != '0' ?
                '(X) LICITADO  | (&nbsp;&nbsp;) NÃO LICITADO' : '(&nbsp;&nbsp;) LICITADO  | (X) NÃO LICITADO';

            ?>
        </td>
    </tr>
    <tr>
        <td colspan="3" class="td-table">

            <table class="table table-striped table-hover table-condensed" border="1">
                <thead>
                    <tr>
                        <th rowspan="2" class="text-center">
                            ITEM
                        </th>
                        <th rowspan="2" class="text-center">
                            DESCRIÇÃO
                        </th>
                        <th rowspan="2" class="text-center">
                            LICITAÇÃO
                        </th>
                        <th rowspan="2" class="text-center">
                            UF
                        </th>
                        <th colspan="2" class="text-center">
                            QUANTIDADE
                        </th>
                        <th colspan="2" class="text-center">
                            PREÇO R$
                        </th>
                    </tr>
                    <tr>
                        <th class="text-center">SOLICITADA</th>
                        <th class="text-center">ATENDIDA</th>
                        <th class="text-center">UNITÁRIO</th>
                        <th class="text-center">TOTAL</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $i = 1;
                    $t = 0;
                    foreach ($this->view->result as $value):

                        ?>
                        <tr>
                            <td><?= $i++; ?></td>
                            <td class='discricao'><?= $value['name']; ?></td>
                            <td><?= $value['biddings_number'] ?? 'NL'; ?></td>
                            <td><?= $value['uf']; ?></td>
                            <td><?= $q = intval($value['quantity']); ?></td>
                            <td><?= $q2 = intval($value['delivered']) > 0 ? intval($value['delivered']) : ''; ?></td>
                            <td><?= number_format($v = $value['value'], 2, ',', '.'); ?></td>
                            <td>
                                <?php
                                    $acc = 0;
                                    $q2 = $q2 > 0 ? $q2 : 0;
                                    $acc = $q2 > 0 ? $q2 * $v : $q * $v;
                                    $t += $acc;
                                ?>
                                <?= number_format($acc, 2, ',', '.'); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6"></td>
                        <td>
                            Total
                        </td>
                        <td>
                            R$ <?= number_format($t, 2, ',', '.'); ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </td>
    </tr>
    <tr>
        <td class="delivery_date">
            Data de entrega: <strong><?= View::humanDate($value['delivery_date']); ?></strong>
        </td>
        <td class="recebedor">
            RECEBIDO EM ________/________/________<br />
            RECEBEDOR:
        </td>
        <td class="data">
            <?= cfg::htrFileConfigs()->papeleta->cidade ?? '' ?>, <?= strftime('%d de %B de %Y', strtotime('today')); ?>.
        </td>
    </tr>
    <tr>
        <td colspan="8" class="obs">
            OBSERVAÇÃO: O material deve ser entregue junto com a NFE, com os dados bancários na mesma.<br>
            Nota Fiscal Nº: <?= $this->view->result[0]['invoice']; ?>
        </td>
    </tr>
    <tr>
        <td class="assinaturas">
            <div class="content-assinatura">
                <?= $this->view->result[0]['munition_manager']; ?><br />
                <?= $this->view->result[0]['munition_manager_graduation']; ?><br />
                Gestor(a) de Municiamento
            </div>
        </td>
        <td class="assinaturas">
            <div class="content-assinatura">
                <div class="linha-assinatura">
                    PAIOLEIRO DE SERVIÇO
                </div>
            </div>
        </td>
        <td class="assinaturas">
            <div class="content-assinatura">
                <?= $this->view->result[0]['munition_fiel']; ?><br />
                <?= $this->view->result[0]['munition_fiel_graduation']; ?><br />
                Fiel de Municiamento
            </div>
        </td>
    </tr>
</table>
<style>
    body {
        font-size: 12px !important;
        background-color: #fff !important;
    }
    .table-striped > tbody > tr:nth-of-type(2n+1) {
        background-color: #ccc;
    }
    .table-print {
        width: 100%;
        border-collapse: collapse;
        margin: 0px auto;
        text-align: center;
    }
    .recebedor {
        text-align: left !important;
        padding-bottom: 10px;
        padding-top: 10px;
        font-weight: bold;
    }
    .cabecalho {
        font-weight: bold;
        font-size: 14px;
    }
    .tipo-documento, .number, .data {
        text-align: right;
        padding-right: 50px;
    }
    .tipo-documento {
        font-size: 14px;
    }
    .number {
        font-size: 18px;
    }
    .data {
        font-size: 16px;
    }
    .assinaturas {
        padding-top: 36px;
        width: 33%;
    }
    .fornecedor {
        padding: 10px;
        text-align: left;
        padding-left: 50px;
        font-weight: bold;
        font-size: 16px;
        padding-top: 25px;
    }
    .obs, .delivery_date {
        text-align: left;
        padding-left: 50px;
    }
    .delivery_date {
        font-size: 14px;
    }
    .agente-fiscal {
        text-align: left;
        padding-left: 100px;
        padding-top: 25px;
    }
    .content-assinatura {
        width: 100%;
        display: block;
        text-align: center;
    }
    .agente-fiscal .content-assinatura{
        width: 45% !important;
    }
    .linha-assinatura {
        border-top: 2px solid;
        width: 75%;
        margin: 0px auto;
    }
    .discricao {
        text-align: left !important;
    }
    .td-table, .table {
        margin: 0px !important;
        padding: 0px !important;
    }
    .table-condensed > tfoot > tr > td {
        padding: 2px !important;
    }
</style>