<ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a><i class="fa fa-user fa-fw"></i> <?= $this->view->userLoggedIn['name']; ?></a>
            </li>
            <li>
                <a href="<?= APPDIR; ?>acesso/editar/id/<?= $this->view->userLoggedIn['id']; ?>"><i class="fa fa-gear fa-fw"></i> Configurações</a>
            </li>
            <li class="divider"></li>
            <li><a href="<?= APPDIR; ?>acesso/logout/"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->