<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="page-header"><?= $this->view->title ?></h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-table fa-fw"></i> Formulário de Cadastro
                    </div>
                    <div class="panel-body">
                        <div id="resultado"></div>
                        <form action="<?= $this->view->controller; ?>registra/" method="post" id="form">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>UASG</label>
                                        <input type="text"
                                               id="uasg"
                                               name="uasg"
                                               placeholder="UASG da OM"
                                               class="form-control"
                                               maxlength="6"
                                               required>
                                        <p class="help-block">UASG (Deve ser um número <b>INTEIRO</b>)</p>
                                    </div>

                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text"
                                               id="name"
                                               name="name"
                                               placeholder="Nome da OM"
                                               class="form-control"
                                               maxlength="100"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Indicativo Naval</label>
                                        <input type="text"
                                               id="naval_indicative"
                                               name="naval_indicative"
                                               placeholder="Indicativo Naval da OM"
                                               class="form-control"
                                               maxlength="6"
                                               required>
                                        <p class="help-block">Ex.: QRTDIS; CITBEL.</p>
                                    </div>

                                    <div class="form-group">
                                        <label>Agente Fiscal</label>
                                        <input type="text"
                                               id="fiscal_agent"
                                               name="fiscal_agent"
                                               placeholder="Nome do Agente Fiscal"
                                               class="form-control"
                                               maxlength="100"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Agente Fiscal Posto</label>
                                        <input type="text"
                                               id="fiscal_agent_graduation"
                                               name="fiscal_agent_graduation"
                                               placeholder="Posto/Graduação do Agente Fiscal"
                                               class="form-control"
                                               maxlength="40"
                                               required>
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Gestor de Municiamento</label>
                                        <input type="text"
                                               id="munition_manager"
                                               name="munition_manager"
                                               placeholder="Nome do Gestor de Municiamento"
                                               class="form-control"
                                               maxlength="100"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Gestor de Municiamento Posto</label>
                                        <input type="text"
                                               id="munition_manager_graduation"
                                               name="munition_manager_graduation"
                                               placeholder="Posto/Graduação do Gestor de Municiamento"
                                               class="form-control"
                                               maxlength="50"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Fiel de Municiamento</label>
                                        <input type="text"
                                               id="munition_fiel"
                                               name="munition_fiel"
                                               placeholder="Nome do Fiel de Municiamento"
                                               class="form-control"
                                               maxlength="100"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <label>Fiel de Municiamento Posto</label>
                                        <input type="text"
                                               id="munition_fiel_graduation"
                                               name="munition_fiel_graduation"
                                               placeholder="Posto/Graduação do Fiel de Municiamento"
                                               class="form-control"
                                               maxlength="50"
                                               required>
                                    </div>

                                    <div class="form-group">
                                        <br>
                                        <button class="btn btn-primary"><i class="fa fa-check"></i> Registrar</button>
                                        <a href="<?= $this->view->controller; ?>" class="btn btn-warning"><i class="fa fa-arrow-left"></i> Voltar</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
