<?php

use App\Helpers\Pagination;
use App\Helpers\View;

$pagination = Pagination::make($this);

?>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h5>Licitações</h5>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus-circle"></i> Novo Registro
                </a>
                <?= $pagination; ?>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Número</th>
                            <th>Descrição</th>
                            <th>UASG</th>
                            <th>UASG Nome</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['number']; ?></td>
                                <td>
                                    <?= $value['description']; ?>
                                </td>
                                <td>
                                    <?= $value['uasg']; ?>
                                </td>
                                <td>
                                    <?= $value['uasg_name']; ?>
                                </td>
                                <td>
                                    <span class="badge badge-danger">
                                        <?= View::humanDate($value['validate']); ?>
                                        <?php if($value['validate'] < date("Y-m-d")): ?>
                                         - VENCIDA
                                        <?php endif ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="item/novo/idlista/<?= $value['id']; ?>" class="btn btn-info btn-sm">
                                        <i class="fa fa-plus-circle"></i> Add
                                    </a>
                                    <a href="item/listar/idlista/<?= $value['id']; ?>" class="btn btn-primary btn-sm">
                                        <i class="fa fa-list"></i> Itens
                                    </a>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                       class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?= $pagination; ?>
            </div>
        </div>
    </div>
</div>
