<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3>Licitações</h3>
                <i class="fa fa-list"></i> <?= $this->view->title; ?><br>
                <a href="<?= $this->view->controller; ?>novo/" class="btn btn-info">
                    <i class="fa fa-plus-circle"></i> Novo Registro
                </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Numero</th>
                            <th>UASG</th>
                            <th>UASG Nome</th>
                            <th>Validade</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->result as $value): ?>
                            <tr>
                                <td><?= $value['numero']; ?></td>
                                <td><?= $value['uasg']; ?></td>
                                <td><?= $value['nome_uasg']; ?></td>
                                <td>
                                    <span class="label label-default">    
                                        <?= date('d-m-Y', $value['validade']); ?>
                                    </span>
                                </td>
                                <td>
                                    <a href="<?= APPDIR; ?>item/novo/idlista/<?= $value['id_lista']; ?>" class="btn btn-info">
                                        <i class="fa fa-plus-circle"></i> Add
                                    </a>
                                    <a href="<?= APPDIR; ?>item/listar/idlista/<?= $value['id_lista']; ?>" class="btn btn-primary">
                                        <i class="fa fa-list"></i> Itens
                                    </a>
                                    <a href="<?= $this->view->controller; ?>editar/id/<?= $value['id']; ?>" class="btn btn-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="#"
                                       onclick="confirmar('Deseja REMOVER este registro?', '<?= $this->view->controller; ?>eliminar/id/<?= $value['id']; ?>')"
                                       class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <nav>
                    <ul class="pagination">
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['previus']; ?>" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <?php foreach ($this->view->btn['link'] as $value): ?>
                            <li><a href="<?= $this->view->controller; ?>ver/pagina/<?= $value; ?>"><?= $value; ?></a></li>
                        <?php endforeach; ?>
                        <li>
                            <a href="<?= $this->view->controller; ?>ver/pagina/<?= $this->view->btn['next']; ?>" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->